version: '3.8'

services:
  # Base de datos PostgreSQL para desarrollo
  postgres:
    image: postgres:16-alpine
    container_name: iso20022-postgres-dev
    environment:
      POSTGRES_DB: iso20022_sim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PgAdmin para administración de BD
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: iso20022-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kuvasz.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_dev_data:

networks:
  default:
    name: iso20022-dev-network
